[build]
#   command = "cd exampleSite && hugo --gc --minify -D -b $URL"
  command = "git submodule update --remote --merge && hugo --gc --minify -D -d https://inquisitive-monstera-cac5f0.netlify.app"
  publish = "public"

[context.production.environment]
HUGO_VERSION = "0.100.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify -D -d https://inquisitive-monstera-cac5f0.netlify.app"

[context.deploy-preview.environment]
HUGO_VERSION = "0.100.2"

[context.branch-deploy]
command = "npm run build && hugo --gc --minify -D "

[context.branch-deploy.environment]
HUGO_VERSION = "0.100.2"
